### ISSUE TITLE
Stands 21-26 Labelled wrong

### ISSUE THREAD

**Issue by blackshadez** [khaleej-vacc/Khaleej-Sector-File-OKAC#8]
Stands 21-26 are labelled in the wrong order from right to left. They are supposed to be from left to right.

<img width="524" alt="image" src="https://github.com/user-attachments/assets/1e8204af-0987-4ca0-a2b2-3234d8645257" />

<img width="412" alt="image" src="https://github.com/user-attachments/assets/842202ff-9dd6-452a-b749-644942d1361e" />

**Comment by Ismailhassan12** [comment]
Fixed by you :) Thanks will be implemented in AIRAC 2501.
